name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.14"]

    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint

      - name: Analyze with pylint
        run: |
          pylint $(git ls-files '*.py')

      - name:  Check secrets
        uses: gitleaks/gitleaks-action@v2.3.9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Claude Analysis
        env:
          CLAUDE_CODE_OAUTH_TOKEN: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
        run:
          chmod +x gh_workflow_assets/claude_review.sh
          ./gh_workflow_assets/claude_review.sh

- name: Check review result
  run: |
    cat /tmp/review.txt
    if [ "$(cat /tmp/review.txt)" != "0" ]; then
      exit 1
    fi

      - name: Static Analysis, Semgrep
        run: |
          pip install semgrep
          semgrep --config p/flask --config gh_workflow_assets/semgrep_ssti.yml --error .

      - name: Static Analysis, Bandit
        run: |
          pip install bandit
          bandit -r .

