name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.14"]

    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint

      - name: Analyze with pylint
        run: |
          pylint $(git ls-files '*.py')

      - name:  Check secrets
        uses: gitleaks/gitleaks-action@v2.3.9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Static Analysis, Semgrep
        run: |
          pip install semgrep
          cat >  /tmp/ssti.yml << EOF
          rules:
            - id: Flask Rule, render_template_string()
              pattern: flask.render_template_string(...)
              message: Potential SSTI - render_template_string()
              languages: [python]
              severity: ERROR
          EOF
          semgrep --config p/flask --config /tmp/ssti.yml --error .

      - name: Static Analysis, Bandit
        run: |
          pip install bandit
          bandit -r .

